name: Release
on:
  release:
    types: [published]
jobs:
  release:
    name: Publish package to PyPI (release)
    runs-on: ubuntu-latest
    environment:
      name: 'pypi'
      url: https://pypi.org/p/hotmodern-python
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        architecture: x64
    - run: pip install nox==2024.4.15
    - run: pip install poetry==1.8.3
    - run: nox --python 3.12
    - run: poetry build
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
