name: TestPyPI
on:
  push:
    branches:
      - main
jobs:
  publish_test_pypi:
    name: Publish package to TestPyPI
    runs-on: ubuntu-latest
    environment:
      name: 'Test PyPI'
      url: https://test.pypi.org/p/hotmodern-python/
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12.4'
        architecture: x64
    - run: pip install poetry==1.8.3
    - run: >-
        poetry version patch &&
        version=$(poetry version | awk '{print $2}') &&
        poetry version $version.dev.$(date +%s)
    - run: poetry build
    - name: Publish package to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
